### PR TITLE
add in missing attributes to fix run

### PR DESCRIPTION
**Pull request by JoshuaSeidel**
Going through the sk-1.2update branch, running it ran into multiple errors. This PR addresses such errors

### CODE REVIEW

**Comment by JoshuaSeidel** [comment]
@aaronlippold @rx294

**Comment by aaronlippold** [comment]
@karikarshivani and @rx294 can you guys validate this and fix it to use inputs so we can merge it. Thanks.

**Comment by aaronlippold** [comment]
@JoshuaSeidel a few minor fixes

**Comment by rx294** [comment]
@JoshuaSeidel please do a fresh compare to the current master and see if this PR is still required.
All the attributes you are adding is already present in the master as `input()` definitions. 
InSpec has replaced `attributes()` with `input()`

**Comment by rx294** [comment]
Closing this PR; the intent of this PR is satisfied in PR https://github.com/mitre/aws-foundations-cis-baseline/pull/95

**Pull request closed without merging**
